
WIDTH = 640
HEIGHT = 670
HEIGHT_HUD = 30
DEFAULT_TILE_SIZE = 16

# Constants for HUD

HUD_MARGIN = 8
HUD_FIREUP_IMAGE = 20
HUD_FIREUP_TEXT = 40
HUD_BOMBUP_IMAGE = 80
HUD_BOMBUP_TEXT = 100
HUD_TIMEUP_IMAGE = 160
HUD_TIMEUP_TEXT = 180

# Constants for Window

WINDOW_WIDTH = 300
WINDOW_HEIGHT = 200

# Constants for selection
## MENU PRINCIPAL
SELECTION_CREATE_SERVER= 0
SELECTION_JOIN_SERVER = 1
SELECTION_QUIT = 2

## MENU_PARAMS_SERVER
SELECTION_PLAY = 0
SELECTION_PORT = 1
SELECTION_NB_PLAYERS = 2

## MENU_PARAMS_CLIENT
CLIENT_SELECTION_PLAY = 0
CLIENT_SELECTION_IP = 1
CLIENT_SELECTION_PORT = 2

# Constants for State of the game
STATE_MENU = 0
STATE_WAITING_CLIENT = 1
STATE_WAITING_SERVER = 2
STATE_PLAYING = 3
STATE_ENDGAME = 4
STATE_LAUNCHING_GAME = 5
STATE_MAP_SELECTION = 6
STATE_PARAMS_SELECTION = 7
STATE_ENDROUND = 8

# Directions

LEFT = 0x1000
RIGHT = 0x0100
UP = 0x0010
DOWN = 0x0001

# Power-ups
FIREUP = 0
BOMBUP = 1
TIMEUP = 2
TIMEDOWN = 3

DEFAULT_EXPLOSION_DURATION = 1000
