
WIDTH = 640
HEIGHT = 640

WINDOW_WIDTH = 300
WINDOW_HEIGHT = 200

SELECTION_CREATE_SERVER= 0
SELECTION_JOIN_SERVER = 1
SELECTION_QUIT = 2

SELECTION_PLAY = 0
SELECTION_PORT = 1
SELECTION_NB_PLAYERS = 2

CLIENT_SELECTION_PLAY = 0
CLIENT_SELECTION_IP = 1
CLIENT_SELECTION_PORT = 2

STATE_MENU = 0
STATE_WAITING_CLIENT = 1
STATE_WAITING_SERVER = 2
STATE_PLAYING = 3
STATE_ENDGAME = 4
STATE_LAUNCHING_GAME = 5
STATE_MAP_SELECTION = 6
STATE_PARAMS_SELECTION = 7

LEFT = 0x1000
RIGHT = 0x0100
UP = 0x0010
DOWN = 0x0001

FIREUP = 0
BOMBUP = 1
TIMEUP = 2
TIMEDOWN = 3

DEFAULT_EXPLOSION_DURATION = 1000
